CREATE USER IF NOT EXISTS 'ngerrets'@'%' IDENTIFIED BY '1234567890';
CREATE DATABASE IF NOT EXISTS wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO 'ngerrets'@'%';
DROP USER IF EXISTS 'root'@'localhost';
CREATE USER IF NOT EXISTS 'super'@'%' IDENTIFIED BY '1234567890';
GRANT ALL PRIVILEGES ON *.* TO 'super'@'%';
FLUSH PRIVILEGES;